### PR TITLE
update BungeeCord injector

### LINKED ISSUE #544: Latest version of BungeeCord gives an error
Plugin dont load 

18:27:34 [WARNING] Exception encountered when loading plugin: floodgate
java.lang.RuntimeException: Failed to inject the packet listener!
at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:73)
at org.geysermc.floodgate.BungeePlugin.onEnable(BungeePlugin.java:64)
at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:266)
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:298)
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.AccessibleObject.isAccessible()" because "accessibleObject" is null
at org.geysermc.floodgate.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:570)
at org.geysermc.floodgate.util.ReflectionUtils.getValue(ReflectionUtils.java:249)
at org.geysermc.floodgate.util.ReflectionUtils.getCastedValue(ReflectionUtils.java:300)
at org.geysermc.floodgate.util.ReflectionUtils.castedStaticValue(ReflectionUtils.java:319)
at org.geysermc.floodgate.inject.bungee.BungeeInjector.inject(BungeeInjector.java:72)
at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:71)
... 5 more

### PR DESCRIPTION
**Pull request by Outfluencer**
closes #544

### CODE REVIEW

**Comment by Outfluencer** [comment]
Fixes incompatibility with https://github.com/GeyserMC/Floodgate/pull/546

**Comment by Camotoy** [comment]
Will this version work on older Bungee versions without the recent changes?

If not, would you be able to still check for the old field and throw an exception telling people to update? If you don't want to do that, that's fine; we can take care of it.

**Comment by Tim203** [comment]
I've verified that this works, ty!
If you're able to re-add it for compatibility with older Bungee versions in the next few hours, feel free to do so.
Otherwise I'm also more than happy to re-add it and get it out of the door.

**Comment by Outfluencer** [comment]
I can do

**Review by Tim203 — APPROVED** [review]

**Pull request merged**
