### PR TITLE
Update to 1.16

### PR DESCRIPTION
**Pull request by D3ATHBRINGER13**
Starting to update for 1.16

### CODE REVIEW

**Comment by D3ATHBRINGER13** [comment]
sorry

**Comment by Tim203** [comment]
Please note that the 1.8 bukkit api version is intentional and the Bukkit -> Spigot renaming is also already done on my local development version (a big update)

**Comment by D3ATHBRINGER13** [comment]
Yea ok, was meaning to ask if that was intentional, and if its already in your fork ill just close this one

**Comment by Tim203** [comment]
Thanks for taking the time for it though

**Pull request closed without merging**
