### PR TITLE
Update build.gradle.kts of bungee module

### PR DESCRIPTION
**Pull request by LittleShyStar02**
Fix java.util.NoSuchElementException: frame-decoder error caused by bungeecord api not updated.

### CODE REVIEW

**Comment by Tim203** [comment]
This doesn't make much sense to me. Do you have an idea why it's caused by an outdated dependency (that we don't include in the final jar)?

**Comment by LittleShyStar02** [comment]
Yes, in the BungeeCord #1868 build, they change a things on netty channel. The error received on prompt was of io.netty in initChannel() method of floodgate that it was outdated because bungeecord change the channel type.

https://github.com/SpigotMC/BungeeCord/commit/b309e4ac50ca44f2cfc06e8d27de33a1f0c77549

**Comment by LittleShyStar02** [comment]
More information of error is here 
https://discord.com/channels/613163671870242838/1297286277187633212

**Comment by LittleShyStar02** [comment]
Sometimes the error appear again, maybe when there are a lot of pings on server

**Pull request closed without merging**
