### PR TITLE
Added PlaceholderAPI device support

### PR DESCRIPTION
**Pull request by rtm516**
Placeholders:
- [x] Device `%floodgate_device%`
- [x] Locale `%floodgate_locale%` and `%floodgate_locale_upper%`
- [x] Version `%floodgate_version%`
- [x] Xbox username `%floodgate_username%`
- [x] Xbox xuid `%floodgate_xuid%`

Using test command `/papi parse me %floodgate_device%%floodgate_locale%%floodgate_locale_upper%%floodgate_version%%floodgate_username%%floodgate_xuid%`
Bedrock:
image

Java:
image

### CODE REVIEW

**Comment by LegacyGamerHD** [comment]
looks good why change placeholder name do

**Comment by rtm516** [comment]
> looks good why change placeholder name do

It fit better with the information it was returning.

**Comment by DoctorMacc** [comment]
Will users ever just want to specify `Bedrock` instead of the exact device? Could you add a configuration that disables per-device names in favour of a single string for all devices?

**Comment by LegacyGamerHD** [comment]
yeah make sense good hob rtm :P

**Comment by LegacyGamerHD** [comment]
> Will users ever just want to specify `Bedrock` instead of the exact device? Could you add a configuration that disables per-device names in favour of a single string for all devices?

ehh no its better to see all devices

**Comment by LegacyGamerHD** [comment]
if you got explain switch bugs or android bugs
for server

**Comment by rtm516** [comment]
I'll add an option to disable specific device descriptors and just have it off by default so it returns the specific device.

**Comment by Tim203** [comment]
We want to keep Floodgate an authentication related plugin, so this is PR doesn't quite fit in. So we decided to make an addons repo somewhere in the future which will give a feature like this a proper place. We don't know yet how this will look like but this means that this PR will be closed.

**Pull request closed without merging**
