### PR TITLE
Hold info for Geyser dump instead of setting it in Geyser

### PR DESCRIPTION
**Pull request by Konicai**
https://github.com/GeyserMC/Geyser/pull/2598 depends on this

### CODE REVIEW

**Comment by onebeastchris** [comment]
what would this do? show the floodgate config in a geyser dump?

**Comment by Konicai** [comment]
Both the floodgate config and git info. https://github.com/GeyserMC/Geyser/pull/2598 kind of explains why it currently doesn't work right now (well sometimes it does, but only once in a blue moon).

The usage of reflection isn't ideal so this issue will just be fixed when floodgate is packaged with geyser.

**Comment by onebeastchris** [comment]
Oh. Thanks for explaining! 
Would definitely help with issues that could be caused by floodgate, e.g. seeing whether linking is on/send-floodgate-data is enabled

**Comment by Tim203** [comment]
I'm going to close this PR because of the Floodgate integration into Geyser. After the integration Geyser would have direct access to the Floodgate info.

**Pull request closed without merging**
