### PR TITLE
Feature: Cloud 2.0, publishing setup fixes

### PR DESCRIPTION
**Pull request by onebeastchris**
- Update to cloud 2.0
- bump floodgate version to 2.2.3
- fix publishing setup - don't publish shadow jars, ensure api/core maven artifacts aren't shaded jars
- update bstats to main version 

TODO's:
- [x] Testing on all platforms

### CODE REVIEW

**Review by Kas-tle — APPROVED** [review]

**Comment by Kas-tle** [comment]
Please ping me before merging this as I still need to update the build process for this repo.

**Comment by onebeastchris** [comment]
I'm currently waiting on Tim's review anyways :p
This is tested and should be working now

**Comment by Kas-tle** [comment]
I have made the required changes

**Review by Camotoy — APPROVED** [review]

**Review by Tim203 — APPROVED** [review]

**Comment by Outfit8TSB** [comment]
thanks to onebeastchris, i can release My Paper Fork ngl.

**Pull request merged**
